apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: pypi-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
