name: Functional Tests
on:
  pull_request:
jobs:
  functest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Run Functional Tests
        env:
          SSL_CERT_FILE: ${{ github.workspace }}/controllers/testdata/tls/ca-bundle.crt
        run: make functest
